# Fetch and update latest `github-actions` pkgs
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
  open-pull-requests-limit: 10
  reviewers:
    - terwer
  assignees:
    - terwer
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
  labels:
    - "npm dependencies"
    - "zhi-root"