version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - terwer
    assignees:
      - terwer
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - "npm dependencies"
      - "zhi-root"

  - package-ecosystem: npm
    directory: "/packages/api-docs"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - terwer
    assignees:
      - terwer
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - "npm dependencies"
      - "api-docs"

  - package-ecosystem: npm
    directory: "/packages/esbuild-config-custom"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - terwer
    assignees:
      - terwer
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - "npm dependencies"
      - "esbuild-config-custom"

  - package-ecosystem: npm
    directory: "/packages/eslint-config-custom"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - terwer
    assignees:
      - terwer
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - "npm dependencies"
      - "eslint-config-custom"

  - package-ecosystem: npm
    directory: "/packages/jest-config-custom"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - terwer
    assignees:
      - terwer
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - "npm dependencies"
      - "jest-config-custom"

  - package-ecosystem: npm
    directory: "/packages/tsconfig"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - terwer
    assignees:
      - terwer
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - "npm dependencies"
      - "tsconfig"

  - package-ecosystem: npm
    directory: "/apps/zhi-cli"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - terwer
    assignees:
      - terwer
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - "npm dependencies"
      - "zhi-cli"

  - package-ecosystem: npm
    directory: "/apps/zhi-core"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - terwer
    assignees:
      - terwer
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - "npm dependencies"
      - "zhi-core"

  - package-ecosystem: npm
    directory: "/apps/zhi-device"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - terwer
    assignees:
      - terwer
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - "npm dependencies"
      - "zhi-device"

  - package-ecosystem: npm
    directory: "/apps/zhi-docs"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - terwer
    assignees:
      - terwer
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - "npm dependencies"
      - "zhi-docs"

  - package-ecosystem: npm
    directory: "/apps/zhi-env"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - terwer
    assignees:
      - terwer
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - "npm dependencies"
      - "zhi-env"

  - package-ecosystem: npm
    directory: "/apps/zhi-log"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - terwer
    assignees:
      - terwer
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - "npm dependencies"
      - "zhi-log"

  - package-ecosystem: npm
    directory: "/apps/zhi-server-blog"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - terwer
    assignees:
      - terwer
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - "npm dependencies"
      - "zhi"
      - "server-modules"
      - "blog"
      - "astro"

  - package-ecosystem: npm
    directory: "/apps/zhi-server-blog-vue"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - terwer
    assignees:
      - terwer
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - "npm dependencies"
      - "zhi"
      - "server-modules"
      - "vue3"
      - "ssr"

  - package-ecosystem: npm
    directory: "/apps/zhi-web-blog"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - terwer
    assignees:
      - terwer
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - "npm dependencies"
      - "zhi"
      - "web-modules"
      - "blog"
      - "nuxt"

  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - terwer
    assignees:
      - terwer
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - "github actions"
      - "ci"