version: "3"
services:
  vue-ssr:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    env_file:
      - ./.env.docker
    restart: no
    user: vue3-ssr
    image: terwer/vue3-ssr:latest